{% set name = "dftflow" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  noarch: python

requirements:
  host:
    - python =3.12
    - pip
    - setuptools
  run:
    - python >=3.12,<3.13
    - ase
    - dftd3-python
    - dftd4
    - h5py
    - jsonschema >=4.18
    - numpy
    - pyscf
    - pyyaml >=6.0
    - pyside6
    - scipy

test:
  imports:
    - basis_set_exchange
    - sella
    - run_opt
    - pyscf
    - pyscf.solvent.smd
  commands:
    - dftflow --help

about:
  home: https://github.com/dhsohn/DFTFlow
  summary: DFTFlow CLI for PySCF/ASE workflows with SMD-enabled PySCF.
  license: MIT

extra:
  recipe-maintainers:
    - daehyupsohn
